

//  ---------- INLCUDED BLOCK: up_counter  ---------- 
module up_counter(
    input wire clk,
    input wire rst_n,
    output reg [3:0] count
);

always @(posedge clk or negedge rst_n) begin
    if (~rst_n) begin
        count <= 4'b0;
    end else begin
        count <= count + 1;
    end
end

endmodule


// Automatically generated by ChipInventor Cloud EDA Tool - 3.15
// Careful: this file (hdl.v) will be automatically replaced
// when you ask tool to generate top Verilog code by clicking
// at BLOCKS button.

module top (

  input wire clk,
  input wire rst,
  output wire [3:0] count

);
//Instances of Modules
up_counter blk1837_4 (
         .clk (clk),
         .rst_n (rst),
         .count (count [3:0])
     );


endmodule
